name: Deploy to dev

env:
  AWS_REGION: us-east-1
  APP_ENV: prod
  NUXT_PUBLIC_MIXIN_CLIENT_ID: 39270fd3-bda7-4ee0-80ef-8eab00564eb6
  NUXT_PUBLIC_MIXIN_API_BASE_URL: "https://api.mixin.one"
  NUXT_PUBLIC_TALKEE_CLIENT_ID: 829283f7-c82d-4931-bad6-a04da459d83b
  NUXT_PUBLIC_TALKEE_API_BASE_URL: "https://talkee-api.aspens.rocks/api"
  NUXT_PUBLIC_BOTASTIC_CLIENT_ID: 03d2e2c3-4258-45e4-beef-ce96af74fa6a
  NUXT_PUBLIC_BOTASTIC_API_BASE_URL: "https://botastic-api.aspens.rocks/api"

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'pandodao'
    steps:
      # prepare
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      # build developer docs
      - run: yarn install --frozen-lockfile

      - name: Build Docs
        run: yarn docs:build

      # build console
      - name: Prepare to build console
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('./yarn.lock') }}

      - name: Install dependencies
        working-directory: ./console
        run: yarn --frozen-lockfile --non-interactive

      - name: Build console
        working-directory: ./console
        run: APP_ENV=${{ env.APP_ENV }} yarn generate

      - name: Move console/.output/public to docs/.vitepress/dist
        run: cp -a console/.output/public docs/.vitepress/dist/console

      # upload to aws
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_ACCESS_KEY_SECRET }}
      - run: aws s3 cp --recursive docs/.vitepress/dist ${{ secrets.S3_URL_DEV }} --acl public-read
      - run: aws s3 cp --recursive docs/.vitepress/dist ${{ secrets.S3_URL_DEV }} --exclude "*" --include "*.html" --cache-control "no-cache" --acl public-read
